// export const SOME_ACTION = 'SOME_ACTION';

// UI
export const DISABLE_ROUTE_FORM = 'DISABLE_ROUTE_FORM';
export const ENABLE_ROUTE_FORM = 'ENABLE_ROUTE_FORM';
export const DISABLE_OBSTACLE_FORM = 'DISABLE_OBSTACLE_FORM';
export const ENABLE_OBSTACLE_FORM = 'ENABLE_OBSTACLE_FORM';
export const SET_OBSTACLE_FORM_STATE = 'SET_OBSTACLE_FORM_STATE';
export const RESET_OBSTACLE = 'RESET_OBSTACLE';
export const SET_UI_MODE = 'SET_UI_MODE';
export const SET_OBSTACLE_PHOTO_STATE = 'SET_OBSTACLE_PHOTO_STATE';
export const SHOW_TOOLTIP = 'SHOW_TOOLTIP';
export const HIDE_TOOLTIP = 'HIDE_TOOLTIP';
export const SET_TOOLTIP_POSITION = 'SET_TOOLTIP_POSITION';
export const SET_TOOLTIP_COORDS = 'SET_TOOLTIP_COORDS';

// Route
export const SET_START_ROUTE_POINT = 'SET_START_ROUTE_POINT';
export const SET_START_ROUTE_PIN = 'SET_START_ROUTE_PIN';
export const SET_FINISH_ROUTE_POINT = 'SET_FINISH_ROUTE_POINT';
export const SET_FINISH_ROUTE_PIN = 'SET_FINISH_ROUTE_PIN';
export const SET_ROUTE_FETCH = 'SET_ROUTE_FETCH';
export const SET_ROUTE = 'SET_ROUTE';
export const CLEAR_ROUTE = 'CLEAR_ROUTE';
export const SET_ROUTE_NODES = 'SET_ROUTE_NODES';
export const CLEAR_ROUTE_NODES = 'CLEAR_ROUTE_NODES';
export const SET_ROUTE_DISTANCES = 'SET_ROUTE_DISTANCES';

// Map
export const SET_MAP = 'SET_MAP';
export const SET_MAP_ROUTE = 'SET_MAP_ROUTE';
export const CLEAR_MAP_ROUTE = 'SET_MAP_ROUTE';
export const SET_MAP_POLYLINES = 'SET_MAP_POLYLINES';
export const CLEAR_MAP_POLYLINES = 'CLEAR_MAP_POLYLINES';
export const SET_TRANSPORT = 'SET_TRANSPORT';
export const SET_VEHICLES_DATA = 'SET_VEHICLES_DATA';
export const SET_VEHICLES_VISIBILITY = 'SET_VEHICLES_VISIBILITY';

// Obstacle
export const SET_OBSTACLES_VISIBILITY = 'CHANGE_OBSTACLES_VISIBILITY';
export const SET_OBSTACLE = 'CHANGE_OBSTACLE';
export const SET_OBSTACLES = 'CHANGE_OBSTACLES';
export const SET_GUESS = 'SET_GUESS';
export const SET_GUESS_POLYLINE = 'SET_GUESS_POLYLINE';
