// export const SOME_ACTION = 'SOME_ACTION';

export const SET_OBSTACLES_VISIBILITY = 'CHANGE_OBSTACLES_VISIBILITY';
export const SET_OBSTACLE = 'CHANGE_OBSTACLE';
export const DISABLE_ROUTE_FORM = 'DISABLE_ROUTE_FORM';
export const ENABLE_ROUTE_FORM = 'ENABLE_ROUTE_FORM';
// TODO: UI action types

export const SET_START_ROUTE_POINT = 'SET_START_ROUTE_POINT';
export const SET_START_ROUTE_PIN = 'SET_START_ROUTE_PIN';
export const SET_FINISH_ROUTE_POINT = 'SET_FINISH_ROUTE_POINT';
export const SET_FINISH_ROUTE_PIN = 'SET_FINISH_ROUTE_PIN';
export const SET_ROUTE_FETCH = 'SET_ROUTE_FETCH';
export const SET_ROUTE = 'SET_ROUTE';
export const CLEAR_ROUTE = 'CLEAR_ROUTE';


export const SET_MAP = 'SET_MAP';
export const SET_MAP_ROUTE = 'SET_MAP_ROUTE';